### ISSUE TITLE
Changed IDs on Geostore

### ISSUE THREAD

**Issue by dt99jay** [cgutteridge/uklidar#1]
Many thanks for this resource, I found it helpful when generating [shapefiles of the LiDAR's coverage](https://bitbucket.org/dt99jay/uk-lidar-open-data-coverage).

Thought I'd mention that the IDs for some of the zip files on geostore.com seem to have changed. For example the [JSON you downloaded for NT60](https://raw.githubusercontent.com/cgutteridge/uklidar/master/downloaded/NT60.json) has the 2m composite DSM with id '3973'. However the current [JSON for NT60 at Geostore](http://www.geostore.com/environment-agency/rest/product/OS_GB_10KM/NT60) has the same zip file with an id of '127688'.

**Comment by cgutteridge** [comment]
Sigh. Annoying but easy to update. I'll rerun my crawler.

On 23/01/2016 23:27, dt99jay wrote:

> Many thanks for this resource, I found it helpful when generating 
> shapefiles of the LiDAR's coverage 
> https://bitbucketorg/dt99jay/uk-lidar-open-data-coverage
> 
> Thought I'd mention that the IDs for some of the zip files on 
> geostorecom seem to have changed For example the JSON you downloaded 
> for NT60 
> https://rawgithubusercontentcom/cgutteridge/uklidar/master/downloaded/NT60json 
> has the 2m composite DSM with id '3973' However the current JSON for 
> NT60 at Geostore 
> http://wwwgeostorecom/environment-agency/rest/product/OS_GB_10KM/NT60 has 
> the same zip file with an id of '127688'
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/cgutteridge/uklidar/issues/1.Web Bug from 
> https://github.com/notifications/beacon/AAfK67wRDhRCW31I0v32zdGDFMIqZwy7ks5pdAP9gaJpZM4HLB_1.gif

## 

Christopher Gutteridge -- http://users.ecs.soton.ac.uk/cjg

University of Southampton Open Data Service: http://data.southampton.ac.uk/
You should read the ECS Web Team blog: http://blogs.ecs.soton.ac.uk/webteam/

**Comment by cgutteridge** [comment]
OK. Scripts rerun and updated version pushed onto github. I wish all my issues could be resolved so easily.

**Comment by dt99jay** [comment]
Thanks!
